<%@ Page Title="Sessions | Iowa Code Camp" Language="C#" MasterPageFile="~/Views/Layouts/Site.master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="headPH" runat="Server">

    <script type="text/javascript">
        $(document).ready(function() {
            $("#sessions").addClass("active");
        });
    </script>

    <style type="text/css">
        div ol {
            padding-left: 25px;
        }
        #sessions ul {
            list-style-type: none;
        }
        #sessions dt {
            font-weight: bold;
            float: left;
            padding-right: 5px;
        }
        #sessions h3 {
            display: block;
            clear: left;
            padding-top: 20px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="normalPH" runat="Server">
        <h1>
        Sessions for Nov 6th</h1>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="primaryPH" runat="Server">
    <div id="sessions">
        <ul>
            <li><h3>iPhone learning curve</h3><p>Experiences writing a iPhone app and having to learn the Mac, Objective C and Cocoa Touch in the process. </p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Ralph Bunker")%></dd></dl></li>
            <li><h3>Your Silverlight app does WHAT?!</h3><p>Out-of-browser, network detection, microphone, webcam, GO! In this session we'll build a Silverlight application that captures media from your computer's webcam and microphone and then uses network detection to determine when it's ok to upload the data "somewhere". We'll cover the ins, outs, and "gotchas" of the API that detects an internet connection as well as what it means to run "out of browser". We'll also dig in to the capture API, learn how to connect to a computer's webcam and microphone, and also record some real data from those devices.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Mike Hodnick")%></dd></dl></li>
            <li><h3>Programming Language Royal Rumble</h3><p>Four programming languages, four implementations of the same project. 15 minutes for each developer to show of their language. Which three will get thrown over the top rope? There can only be one winner in the Programming Language Royal Rumble.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Brandon Carlson")%></dd></dl></li>
            <li><h3>Microsoft Expression Blend and Sketchflow</h3><p>This presentation gives an excellent overview of Microsoft Expression Blend and an overview of how Microsoft Expression Blend with SketchFlow can be a great asset to the entire development cycle. It will cover various tools inside of Blend and demonstrate how to create animations, work with media, and take advantages of Resource files.  It also takes a look at XAML as well as how Blend and Visual Studio work together. Finally it gives details and a demonstration of how Microsoft SketchFlow works and integrates into SharePoint.  </p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Jarrod Edge")%></dd></dl></li>
            <li><h3>Using Django and TDD to version Databases</h3><p>Using the Django application built in the previous session, I will demonstrate how using Django's tools, with South (an open source Django application), and TDD can make database schema versioning and data migration a breeze.  While this session does build on the application developed in Session 1, Session 1 is not a pre-requisite.  This session can stand alone.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Matthew J Morrison")%></dd></dl></li>
            <li><h3>Getting started with FubuMVC</h3><p>Going through the bare minimum required to set up a FubuMVC app. This session will cover initial setup, configuring your FubuRegistry, and getting to know (and love) the _fubu diagnostics feature.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Ryan Rauh")%></dd></dl></li>
            <li><h3>Building Scalable, Fault-Tolerant, Highly Concurrent Systems ... MADE EASY?</h3><p>Akka is the platform for the next generation, event-driven, scalable, and fault-tolerant architectures.  Writing correct, concurrent, fault-tolerant and scalable applications is too hard.  Most of the time it's because we are using the wrong tools and the wrong level of abstraction. Akka is here to change that. akkasource.org In this session we'll walk through what akka is on a high level overview, then I'll explain what we're building at T8Webware and why akka solves some of our hardest problems.  I'll wrap up with a live code example showing the power and simplicity of akka.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Benjamin Metz")%></dd></dl></li>
            <li><h3>Functional Programming for Imperative Junkies [like me]</h3><p>Why is there such a buzz around Functional Programming?  Hype?  Language Politics?  Java backlash? NO Functional Programming was made for our time.  Right now. When complexity threatens to overrun the best of us.  When concurrency is not an option, its a must. If you're an imperative junkie like me and have been rolling around in C#, Java, PHP and Ruby; the world of Haskell, Erlang, F#, Scheme and [shudder] LISP can seem intimidating.  In this session I'll provide an easy to understand overview of FP, the family of languages and a bit of history.  We'll then dive in to some real-life examples from my own experience over the last year in moving to a more functional way of solving problems.  We'll then wrap up with some tips and tricks that I wish someone would have given me when I got my first Haskell book from Amazon.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Benjamin Metz")%></dd></dl></li>
            <li><h3>What's New in the .NET 4.0 BCL</h3><p>With the release of the 4.0 version of the .NET Framework and Visual Studio 2010, there's a lot to take in. In this talk, we'll narrow the focus to the additions to the Base Class Library (BCL), which includes tuples, numerics, I/O, parsing, collections, and other various goodies.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Jason Bock")%></dd></dl></li>
            <li><h3>Introduction to Silverlight Development on Windows Phone 7</h3><p>Take a look at how you can get started developing applications for Windows Phone 7 Series using the free downloadable tools that are now available. Starting off with an overview of the Windows Phone platform, we'll then cover the new application model, developing apps, leveraging services unique to the phone, and more. This session is very "demo heavy" with most of our time spent building an application that shows off the various phone features.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Jeff Brand")%></dd></dl></li>
            <li><h3>A FIRST LOOK AT AXUM</h3><p>Axum is a programming language launched as an incubation project within Microsoft DevLabs. Unlike traditional object-oriented languages, Axum is an actor-oriented language that uses principles of isolation, actors, and message-passing to increase application safety, responsiveness, scalability, and developer productivity. This presentation will include a walkthrough of small sample applications written in Axum for Visual Studio 2010 that offers an overview of the Axum language.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Jeff Ferguson")%></dd></dl></li>
            <li><h3>Smooth Streaming in Silverlight with the Silverlight Media Framework</h3><p>The Silverlight Media Framework was developed from best practices learned from the development of such notable implementations of smooth streaming with Silverlight as the Olympics, Wimbledon, Sunday Night Football and the Tour de France. In this session, we'll go over the SMF, when you should use it and we'll finish by building an app that highlights the most fun and interesting elements of SMF.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Vince Bullinger")%></dd></dl></li>
            <li><h3>Jumpstart: Silverlight</h3><p>In this session attendees will be introduced to Silverlight and we will work through some beginner examples in this new, rapidly evolving technology, which leverages all of the power of the .NET Framework and ASP.NET platform, while providing the richest user interfaces yet seen in the web space.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Kevin Grossnicklaus")%></dd></dl></li>
            <li><h3>Real World Line-of-Business Development in VS.NET 2010, Silverlight 4.0, and RIA Services</h3><p>Are you intrigued with Silverlight 4 as a way to build Line-of-Business applications? Want to know what the Entity Framework is and what it will do for your projects? Have you always wanted to know how to quickly set up a project and get a flexible architecture in place on which to grow an enterprise caliber application? Then this session is for you. Within the course of one presentation we will throw out PowerPoint and CODE, CODE, CODE (and answer a few questions as we CODE). During this session we will build a front to back .NET Line-of-Business application using: Visual Studio.NET 2010 and C#; SQL Server 2008 R2; Entity Framework 4.0; Silverlight 4.0 and RIA Services. . This will be a very interactive session and I'll try to answer any and all questions as I code (in addition to juggling flaming bowling pins and swallowing a sword).If you are tired of presentations with little or no code and just want to see how all of these pieces fit together into a workable Line-of-Business application then this session is for you. </p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Kevin Grossnicklaus")%></dd></dl></li>
            <li><h3>Tools of the Framework Developers</h3><p>Each year, more and more frameworks are being developed to make our coding easier.  However, there are a handful of concepts within the .NET framework that enable us to create our own frameworks.  In addition to framework development, a developer who is well versed in these concepts can use them to make their other development efforts more powerful and flexible. Topics covered will include:
                Delegates
                Delegate Chaining
                Lambda functions
                Generics</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Nate Adams")%></dd></dl></li>
            <li><h3>The Low-Hanging Fruit of HTML5</h3><p>This session will provide you a quick run around some of the beginner aspects of HTML5 and help you in ensuring that your current sites could start taking advantage its features.  Some specific elements being covered include using the audio and video elements, enhancements to webforms, and how to use microformats.  This session assumes a basic knowledge of hand-coding web pages and basic usage of JavaScript.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("James Eggers")%></dd></dl></li>
            <li><h3>PowerShell 2.0 for Developers</h3><p>PowerShell is Microsoft's next-generation command-line shell and scripting language. This session will discuss why you need it, how to use it, and what makes it different from any other shell on any platform. Beyond its traditional uses for system administration, PowerShell provides full access to .NET for Read-Eval-Print loops (REPL), rapid prototyping, object exploration and extensibility. After an overview of language features and what's new in version 2.0, we dive into an interactive demo, so come prepared with questions you have or problems we can solve together. I will also share lessons learned building posh-git, a PowerShell environment for Git.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Keith Dahlby")%></dd></dl></li>
            <li><h3>Git More Done</h3><p>You've seen the intro, you've cloned from GitHub, but you're still not convinced Git's learning curve is worth the climb. This session aims to shed some light from the real world on how Git is different, why the differences matter, and introduce some features and use cases you never knew you couldn't live without. Topics covered will include interactive rebase, interactive add, bisect, reflog and more.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Keith Dahlby")%></dd></dl></li>
            <li><h3>Introduction to the MVVM UI Pattern</h3><p>Whether you're writing a Silverlight or WPF application, if the UI is written in XAML, you need to be looking at the MVVM (Model-View-View Model) pattern.  Taking advantage of XAML's rich data-binding capabilities, MVVM allows for a clean separation between the UI and the application logic.  In this talk, I'll cover the basic hows and whys of this pattern in the context of building a simple application from scratch. </p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Adam Barney")%></dd></dl></li>
            <li><h3>Modern Version Control Systems: Choosing a Tool That Meets Your Needs</h3><p>Version control is one of the most critical tools developers use: from keeping files safe, to tracking revisions, to enabling effective collaboration. Often, a VCS is selected on the basis of what is easily available or has previously been used; without consideration for the needs of the developers, how well it protects the work they create, or how it helps them work more effectively.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Robert Altman")%></dd></dl></li>
            <li><h3>Debugging .Net applications in a production environment</h3><p>Have you ever had a performance issue, memory leak, crash or cryptic exception that you can only reproduce in a production environment? May be is time to bring the big guns and use tools like WinDBG, SOS or DebugDiag to  shed some light on the issue. This session also shows new features on Visual Studio 2010 and .Net 4.0 to work with memory dumps.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Cesar Mendoza")%></dd></dl></li>
            <li><h3>Dive into ADO.NET Entity Framework</h3><p>Entity Framework 4.0 is Microsoft’s data access mapping technology available to developers for working with data in their applications. This session is a dive into the capabilities and limitations of Entity Framework 4.0 where we cover a variety of topics including object to table mappings, code generation, POCO support and much more. Find out where it fits in your tool belt and how you can use it to streamline your development process.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Mike Benkovich")%></dd></dl></li>
            <li><h3>NuPack - Package Management for .NET</h3><p>We all do some sort of package management, whether we realize it or not. Many of us spend quite a bit of time doing it and we don't have to anymore. What is package management? Why is that good for me? Microsoft has announced package management for .NET through a tool called NuPack that is a collaborative effort between Microsoft and the open source community (including the Nu team). We'll start from ground zero and discuss package management in general, then take a look at NuPack from where it is now to where we hope it is going. This will start out as a presentation and at the end become an open discussion to generate ideas about where we can take the tool. </p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Rob Reynolds")%></dd></dl></li>
            <li><h3>Improve Your App with Code Analysis</h3><p>There are a lot of things that can go wrong with your code and most of them are not obvious. Thankfully there are several free tools that exist that you can automate to find violations of best practices. We’ll cover the usage of FXCop, StyleCop and Nitriq and discuss why it is important to follow each rule and when it is appropriate to ignore a rule violation.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Jon von Gillern")%></dd></dl></li>
            <li><h3>ASP.NET Dynamic Data</h3><p>ASP.NET Dynamic Data is a framework for creating Data-Driven (CRUD) Applications quickly and easily.  It was originally included with Visual Studio 2008 SP1 and is built on top of the existing ASP.NET framework.  It utilizes the power of new .NET features (LINQ, Entity Framework, URL Routing) to Dynamically create an entire website based off a Domain Model and Metadata.  Dynamic Data is not code generation; the run-time generated site is easily customizable through metadata, and parts of the Dynamic Data framework can be integrated into existing websites. This will be a three part presentation.  First, we’ll cover the basics of creating a Dynamic Data website and build an entire site from scratch.  Second, we’ll dig into the Framework to see how all this functionality is possible.  We’ll cover the DynamicField control and FieldTemplates.  And third, we’ll integrate Dynamic Data controls into an existing website to see what problems it can solve quickly and easily.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Aaron Hoffman")%></dd></dl></li>
            <li><h3>Curriculum Development Workshop</h3><p>If you were the king of the school, how would you mold fresh talent into a programmer you would like to have on your development team? It seems everyone has opinions what beginners need to learn to be employable and enjoyable in the workforce. This session will try to create a 2-year college curriculum to meet our demanding needs.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Dustin Thostenson")%></dd></dl></li>
            <li><h3>Introduction To Subversion</h3><p>This session will show you how to get up and running on Subversion within an hour. The demo will use VisualSVNServer and TortoiseSVN. We will start from zero by downloading the opensource tools, and end with a fully functional repository complete with branches and permissions. We will then work through a typical feature development cycle with commits, reverts, compares, etc.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Kirstin Juhl")%></dd></dl></li>
            <li><h3>How to Conquer Startup Fever</h3><p>Most of us developers have that bug, you know the one, the itch, the drive to create, to start something. But, the inertia of the couch is sometimes just too much to overcome. We've got the skill and the ideas, but sometimes we just need a kick. One terrific kick is Startup Weekend (Nov 19-21, go sign up ,we'll wait). In this session Andy Pickett describes how Startup Weekend provided that launch pad and just enough boost for his teammates to get something real off the ground. That something is QONQR, the GeoSocial Game of World Domination! This session will be 1 part code, 1 part business, 1 part game theory, and 100% awesome. We'll walk through the process of the startup from pitch to design to alpha to beta and beyond. It will include a tour through the (3 week old) codebase that is QONQR (including a Mobile Web front end using ASP.Net MVC 2 and jQuery, a Tactical Command Center written in Silverlight, and SQL Server back end). Hopefully this will just be a fun, maybe inspiring conversation about getting something started. There will be absolutely no best practices or patterns displayed, as well as no legally binding business advice of any kind, this much we promise you.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Andrew Pickett")%></dd></dl></li>
            <li><h3>Entrepreneurship Q & A.</h3><p>You bring the questions, and the answers.  Scott Davis will facilitate an open forum on what it means to be self-employed in the Technology industry.  Whether it is consulting, building a product for sale, or some service in between, all topics are open to discussion, including the non-technical topics such as payroll, insurance, and venture capitalist.  The session will open by building an agenda from the session participants.  Scott will offer opinions on any topics he can, seeking additional advice from the audience.  Together we’ll crowd-source the best solutions to your startup questions.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Scott Davis")%></dd></dl></li>
            <li><h3>Introduction to BDD with SpecFlow</h3><p></p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Darren Cauthon")%></dd></dl></li>
            <li><h3>Outside-in development with MVC and Specflow</h3><p></p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Darren Cauthon")%></dd></dl></li>
            <li><h3>Getting Dirty with Android</h3><p>You’ve learned how to get set up to develop for the Android platform and how to publish an app.  Eclipse is all ready to go and you’ve got a killer idea.  Now what?  In this session, we will talk about many of the key concepts you will need to understand to develop good applications for the Android platform.  We will discuss concepts such as layout, styling, asynchronous tasks, lifecycle management, menus, dialogs and custom graphics.  This will be a code-heavy session where we will be getting our hands dirty to illustrate these concepts in action.</p><dl><dt>Speaker</dt><dd><%= Html.SpeakerLink("Brent Edwards")%></dd></dl></li>
            
        </ul>
    </div>
</asp:Content>
